src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilder.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/util/TimeUtils.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilderTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/util/AnonymizeUtilsTest.java

impl'd TelemetryMessageBuilderTest (#3)

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilder.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/util/TimeUtils.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilderTest.java

using LocalDateTime in start/finished timestamp to respect date changes

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/configuration/TelemetryConfiguration.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/configuration/TelemetryConfigurationTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceTest.java

impl'd TelemetryConfigurationTest (#5)

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/configuration/TelemetryConfiguration.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceFactory.java
src/main/java/com/redhat/devtools/intellij/telemetry/ui/TelemetryNotifications.java
src/main/java/com/redhat/devtools/intellij/telemetry/ui/preferences/TelemetryConfigurable.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/configuration/TelemetryConfigurationTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceIntegrationTest.java

moved mockable deps to methods (was: statically initialized) (#10)

---

README.md

chore: Add project status to README.md

---

.github/workflows/conventionalCheck.yml
.github/workflows/release.yml
.gitignore
Jenkinsfile

chore: Add Jenkinsfile

---

Jenkinsfile

chore: Fix Jenkinsfile to handle plugin zip file with spaces

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore: Prepare for 0.0.1

---

build.gradle

chore: Generate Zip file with version

---

.github/workflows/IJ.yml

chore: added test against IC-2021.1

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilder.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilderTest.java

fix: ignore & warn properties using null key/value (#23)

---

.github/workflows/ci.yml
.github/workflows/release.yml
build.gradle
gradle.properties

chore: use intellij gradle plugin 1.1.4 (#35)

---

.github/workflows/IJ.yml
build.gradle

chore: add plugin verifier to github actions (#40)

---

Jenkinsfile

chore: set Jenkins to use jdk11

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilder.java
src/main/java/com/redhat/devtools/intellij/telemetry/ui/TelemetryNotifications.java
src/main/java/com/redhat/devtools/intellij/telemetry/ui/utils/JBLabelUtils.java
src/main/java/com/redhat/devtools/intellij/telemetry/ui/utils/NotificationGroupFactory.java

fix: API breakage as reported by marketplace (#38)

---

.github/workflows/IJ.yml
gradle.properties

chore: added verification for IC-2021.3 & IC-2022.1 (#49)

---

Jenkinsfile

chore(build): upload build artifacts via sftp (was: rsync) (#52)

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Environment.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/IDE.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Plugin.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceFactory.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/EnvironmentTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/Fakes.java

fix: report product name with edition (was: only prod name)(#54)

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/configuration/TelemetryConfiguration.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Application.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Environment.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/IDE.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Platform.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryService.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/UserId.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/segment/IdentifyTraits.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/segment/IdentifyTraitsPersistence.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/segment/SegmentBroker.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/util/Directories.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/util/FileUtils.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/EnvironmentTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/Fakes.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceIntegrationTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/segment/IdentifyTraitsPersistenceTest.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/segment/SegmentBrokerTest.java

fix: only send identify events if traits changed (#46)

---

gradle.properties
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/UserId.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/UserIdTest.java

fix: validate uuid loaded from disk (#68)

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilder.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryService.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryServiceFactory.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/segment/IdentifyTraitsPersistence.java

this was found in the review of telemetry for JBoss Tools: https://github.com/jbosstools/jbosstools-base/pull/760#discussion_r1235406048

fix: use a fresh builder each time a new msg is built

---

build.gradle
gradle.properties
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilderIntegrationTest.java

Signed-off-by: Fred Bricon <fbricon@gmail.com>

build: update segment-java to 3.4.0 and gson to 2.10.1

---

build.gradle
gradle.properties
src/main/java/com/redhat/devtools/intellij/telemetry/core/IMessageBroker.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Environment.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Plugin.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilder.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/segment/SegmentBrokerFactory.java
src/test/java/com/redhat/devtools/intellij/telemetry/core/service/TelemetryMessageBuilderTest.java

fix: refactor builder to use plugindescriptor

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/configuration/limits/LimitsConfigurations.java

fix: corrected url to remote configuration (#90)

---

src/main/java/com/redhat/devtools/intellij/telemetry/core/configuration/limits/EventCounts.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/service/segment/SegmentBroker.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/util/BasicGlobPattern.java
src/main/java/com/redhat/devtools/intellij/telemetry/core/util/FileUtils.java

fix: fixed marketplace plugin verifier complaints (#97)

---

.github/workflows/nightly.yml

chore: publish a nightly build
